config/routes.rb
CroquetClub::Application.routes.draw do
  resources :bookings

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'croquet#Home'
  match '/aboutTheClub' => 'croquet#AboutTheClub', via: :get
  match '/howToJoin' => 'croquet#HowToJoin', via: :get
  match '/whatYouNeed' => 'croquet#WhatYouNeed', via: :get
  match '/programme' => 'croquet#Programme', via: :get
  match '/newsLetters' => 'croquet#NewsLetters', via: :get
  match '/clubMatters' => 'croquet#ClubMatters', via: :get
  match '/howToGetThere' => 'croquet#HowToGetThere', via: :get 
  match '/bookALawn' => 'croquet#BookALawn', via: :get
  match '/links' => 'croquet#LinksToCroquetSites', via: :get
  match '/admin' => 'croquet#AdminLogin', via: :get
  match '/signUp' => 'croquet#SignUp', via: :get
   match '/signIn' => 'croquet#SignIn', via: :get

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
 
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :lawn
  attr_accessible :lawn_id, :time_start, :time_end
end

app/models/lawn.rb
class Lawn < ActiveRecord::Base
  attr_accessible :lawn_id, :title, :availability
  has_one :Booking
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :date, :title, :newsletter
  mount_uploader :newsletter, NewsletterUploader
end

app/models/programme.rb
class Programme < ActiveRecord::Base
  attr_accessible :title, :date, :description
  validates_presence_of :title, :date, :description
  validates_uniqueness_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < InheritedResources::Base
end

app/controllers/croquet_controller.rb
class CroquetController < ApplicationController
  def Home
    @title = " Home"
  end

  def AboutTheClub
    @title = "About The Club"
  end

  def HowToJoin
    @title =" How To Join"
  end

  def WhatYouNeed
    @title = "What You Need"
  end

  def Programme
    @title = Date.current.year
    @programme = Programme.where("date >= ?", Date.today)
  end

  def NewsLetters
    @title = "NewsLetters"
    @newsletters = Newsletter.all
  end

  def ClubMatters
    @title = "Club Matters"
  end

  def HowToGetThere
    @title = "How To Get There"
  end

  def BookALawn
     @title = "Book A Lawn"
  end

  def LinksToCroquetSites
    @title = "Links To Croquet Sites"
  end
  
  def AdminLogin
    @title = "Admin Login"
  end
  
  def SignUp
     @title = "Sign Up"
  end
  
  def SignIn
     @title = "Sign In"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title 
    base_title = "CHEAM CROQUET & BOWLS CLUB"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/croquet_helper.rb
module CroquetHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lawn_id %><br>
    <%= f.number_field :lawn_id %>
  </div>
  <div class="field">
    <%= f.label :time_start %><br>
    <%= f.datetime_select :time_start %>
  </div>
  <div class="field">
    <%= f.label :time_end %><br>
    <%= f.datetime_select :time_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <thead>
    <tr>
      <th>Lawn</th>
      <th>Time start</th>
      <th>Time end</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.lawn_id %></td>
        <td><%= booking.time_start %></td>
        <td><%= booking.time_end %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lawn:</strong>
  <%= @booking.lawn_id %>
</p>

<p>
  <strong>Time start:</strong>
  <%= @booking.time_start %>
</p>

<p>
  <strong>Time end:</strong>
  <%= @booking.time_end %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/croquet/AboutTheClub.html.erb
<br> </br>

<h1>About The Club</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus non tellus ut condimentum. Sed fermentum ac lorem vitae congue. Donec sed cursus justo, a fermentum odio. Proin venenatis tempus libero, et hendrerit dui tristique eu. Curabitur quis ligula cursus, porttitor tellus non, luctus est. Morbi adipiscing sapien lacinia lorem tincidunt rhoncus. Pellentesque faucibus egestas erat, sit amet hendrerit magna. Nullam gravida mauris ligula, a sagittis tortor sollicitudin ut. Pellentesque sed tristique neque, vitae tincidunt nibh. Nullam lacinia mauris in ante imperdiet, id viverra elit rhoncus.

  Praesent est metus, auctor vitae lobortis nec, feugiat in lectus. In tincidunt, velit id lobortis condimentum, orci nisl blandit nulla, a ornare tellus nulla et mauris. Proin venenatis libero quam, at consequat mi consequat id. Donec ut semper lorem. Ut sit amet nisl cursus, egestas ante at, imperdiet ligula. Phasellus nisi nisl, vestibulum id sem sed, viverra fermentum mauris. Praesent aliquet molestie turpis at pretium. Duis faucibus fermentum ipsum, a gravida ipsum sodales in.

 <p> Vestibulum cursus, ante a rhoncus facilisis, nisi massa interdum justo, at placerat purus nisl fringilla felis. Vivamus hendrerit dui sit amet erat vulputate, nec tincidunt lectus cursus. Maecenas scelerisque eu erat vel venenatis. Mauris sapien est, gravida vitae dolor sed, rutrum porttitor sem. Integer mattis odio mi, id convallis nunc malesuada viverra. Aenean eleifend rutrum mi, eget dignissim velit pretium at. Nunc sed metus egestas, pharetra odio a, varius orci. Etiam facilisis id tellus vel lobortis. Sed bibendum pharetra placerat. Proin hendrerit, nisl sed sagittis molestie, magna dui fringilla libero, sed vulputate augue lorem sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque sed tempus enim. Duis ac cursus erat. Nunc dapibus laoreet ipsum, eget consequat tortor imperdiet ut. Aliquam ultrices risus a auctor tincidunt.</p>

app/views/croquet/AdminLogin.html.erb
<h1>Admin Login</h1>

app/views/croquet/BookALawn.html.erb
<br> </br>
<h1>Book A Lawn</h1>
<p>Find me in app/views/croquet/BookALawn.html.erb</p>

app/views/croquet/ClubMatters.html.erb
<br> </br>

<h1>Club Matters</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed libero ultricies, tincidunt justo eu, pharetra eros. Donec dignissim, lacus at dictum rutrum, dui nisl condimentum ante, eget ultrices ante ligula a lacus. Quisque ipsum arcu, feugiat bibendum molestie ac, lacinia malesuada risus. Donec id tempus velit. Duis sollicitudin massa dignissim elit vulputate pulvinar. 
 <p> Sed blandit mattis luctus. Etiam eleifend tortor vitae purus placerat pellentesque. Quisque vel dui sed ligula luctus dapibus sed in nisl. Mauris nec fermentum nunc, quis pulvinar odio. Proin posuere condimentum metus, vel aliquet lorem sodales quis. In cursus nisl vel massa iaculis mollis. Aenean lacinia elit sed nunc pharetra lobortis. Curabitur elit velit, aliquet lobortis nisl at, consequat aliquet nulla. Quisque commodo et nibh eget rhoncus. Duis nibh mi, cursus et commodo vel, eleifend ac ante. 
   Suspendisse suscipit nec justo nec venenatis.</p>

  
<p>Suspendisse non dolor lorem. Praesent lacus lorem, interdum et fermentum eget, laoreet sed mi. Fusce ac congue massa. Suspendisse iaculis tortor id purus blandit, sodales sagittis dui sodales. Proin dui ante, adipiscing eget ligula sed, rhoncus condimentum nisl. Aliquam nec dui volutpat, tincidunt elit id, hendrerit turpis. Curabitur tempor tellus a convallis rutrum. Morbi tempus luctus lacus sed ullamcorper. Phasellus et augue nec massa interdum mollis et quis nisl. Nam est orci, pretium eget lorem cursus, mollis suscipit arcu.</p>

app/views/croquet/Home.html.erb
<br> </br>

<h1>Home</h1>

<p ><b>-Membership</b></p>

For our 2013/14 year we welcome 15 new members – David and Julia Aldous- Cook, Naomi Aruliah, Mansoureh de Brett, Thelma Drake, Andrew and Gillian Eperson, Geoff Gunton, Pam Hudson, Jean Hunt, Yvonne Jessop, Sue Muckle, Liz Swinton, Byron Theo and Barbara Verdie.

<p>The membership of the Club is currently 78, with 66 primarily playing Croquet and 12 primarily playing Bowls.</p>

<p><b>-Club sessions</b></p>

There are Club sessions for Golf Croquet on Tuesday and Wednesday mornings, Thursday and Sunday afternoons and Wednesday evening. There is one session for Association Croquet each Sunday morning and two sessions for Bowls on Monday and Wednesday afternoons.

Some members have very kindly agreed to try to attend some of the Golf Croquet Club sessions on a regular basis so that any member turning up has someone to play with. These are normally the Tuesday and Wednesday morning and Thursday afternoon sessions. If you arrive at a Club session and there is no one else there it is a good opportunity to set the hoops out and do some practice. This sort of practice can be very valuable in improving your skills. 

<p>Please play on the full lawn when you can as it is much better practice. The half lawns should normally only be used when there are more than 8 members at a session.</p>

<p><b>-Coaching</b></p>

The Club now has 3 qualified Croquet coaches – Ian Cobbold for Golf and Neil Coote and Geoff Gunton for Association. 

Ian has already done some coaching sessions this year and will be offering some more dates shortly, giving initial priority to newer members. Neil and Geoff would be glad to hear from any members who would like to learn (more) about Association croquet.

<p>If any members would like coaching for Bowls please contact John Davies or Ben Bennett.</p>

app/views/croquet/HowToGetThere.html.erb
<br> </br>

<h1>How To Get There</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis pellentesque vestibulum. Vivamus sed est vitae orci iaculis aliquam et eget tellus.Sed aliquet turpis vitae dolor laoreet sagittis.</p> 
<p> Curabitur posuere arcu mi, et mattis mauris malesuada eget. Suspendisse justo lectus, convallis vel dui sit amet, placerat pretium nulla. Duis quis hendrerit leo. Ut euismod augue et nisi feugiat, egestas consequat risus convallis. Nullam sed sodales orci, eu mattis nunc. Quisque convallis purus ac ullamcorper feugiat. Cras porta, lorem eu molestie scelerisque, nibh turpis vulputate tellus, nec ultricies velit massa at eros. Suspendisse pharetra a mi bibendum viverra.</p>
<p> Suspendisse sodales et felis quis venenatis. Maecenas rhoncus nisl ac erat pulvinar placerat.In at tincidunt mi, quis interdum sem.</p>

<%=image_tag"dashfly-slide2.gif", :size => "300x300"%>

app/views/croquet/HowToJoin.html.erb
<br> </br>

<h1>How To Join</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in arcu eu felis cursus blandit. Pellentesque leo enim, adipiscing ut fringilla at, consequat vitae neque. Integer et aliquam mi. Fusce at ipsum ipsum. Mauris dictum risus eu ligula faucibus, eu porttitor mi lobortis. Nulla vitae sem dignissim, imperdiet velit non, hendrerit magna. Curabitur laoreet urna eu tincidunt congue. Duis quis nibh tincidunt elit egestas consectetur at quis lectus. </p>

<p>Proin congue at dui ut imperdiet. Nam leo erat, suscipit at aliquet vel, tristique a nisi. Etiam convallis viverra massa id volutpat. Nam gravida nisl id mauris tristique rhoncus. Mauris nec vehicula ante, non auctor enim. Vivamus quis nulla sit amet ligula vehicula mollis in fringilla mi. Donec nec purus metus. Morbi vulputate erat eu libero porttitor, id bibendum orci sodales. Ut laoreet enim eu diam congue sagittis. Mauris facilisis porttitor tellus, a elementum urna tincidunt vel. Donec placerat nibh vitae arcu interdum, vel accumsan risus congue.</p> 

<p>Maecenas arcu libero, rutrum in arcu eget, dignissim laoreet dui. Nulla sollicitudin pharetra metus vitae varius. Maecenas nec suscipit mauris, id auctor eros. Nulla a dui risus. Vivamus at lacus nec dui facilisis sodales. Vivamus eu ullamcorper neque. Nam eu adipiscing ipsum. Nulla facilisi. Donec non scelerisque est. Mauris aliquam tempus vulputate. Maecenas fringilla sed ipsum dapibus congue. In ipsum leo, elementum ac leo eget, ultricies tempor libero. Proin consequat vitae libero ultrices rhoncus.</p>

<p>Mauris eleifend tincidunt dolor, tincidunt lobortis velit congue sed. Sed eu venenatis ipsum, consectetur varius risus. Ut cursus auctor velit eget gravida. Nulla magna erat, suscipit eget ornare quis, tempus id libero. Vestibulum venenatis quis sapien eu suscipit. Etiam iaculis eros tortor, vel dapibus augue tempus sed. Etiam euismod orci ut nunc malesuada vestibulum. Proin eu nibh vel lacus vehicula posuere. Ut mollis nisl metus, sed rutrum felis dignissim non. Etiam sit amet mauris quis orci mattis malesuada id venenatis dui. </p

app/views/croquet/LinksToCroquetSites.html.erb
<br> </br>

<h1><p>Links To Croquet Sites :</p></h1>
1. SECF:
<p><%= link_to image_tag("secf.jpg"), "http://www.southeastcroquet.org.uk/" %></p>
2. Croquet Association:
<p><%=  link_to image_tag("croquet.gif"), "http://www.croquet.org.uk/" %></p>
3. Croquet Academy
<p><%= link_to image_tag("academy.gif"), "http://www.thecroquetacademy.com/" %></p>
4. Croquet Equipment
<p><%= link_to image_tag("oxford.gif"), "www.oxfordcroquet.com" %></p>
5. Croquet Glossary
<p><%= link_to image_tag("cornwall.gif"), "http://cornwall-croquet.org.uk/croquet_glossary.htm" %></p>

app/views/croquet/NewsLetters.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="programme.css">
</head>

<br> </br>
<h1>News Letters</h1>

<table id="newsletter">
    <thead>
        <tr>
          <th>Title</th>
          <th>Date</th>
      
        </tr>
    </thead>
  <tbody>
  <!-- Function to group the newsletter by year -->
    <% @newsletters = Newsletter.group(:date) %>
    <!-- Function to read the newsletters from database -->
    <% @newsletters.each do |newsletter| %>
        <tr>
          <td><%= link_to newsletter.title, newsletter.newsletter_url %></td>
          <td><%= newsletter.date %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/croquet/Programme.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="programme.css">
</head>
<br> </br>

<h1><%= Date.current.year %> Programme </h1>

<table id="programme">
    <thead>
        <tr>
          <th>Title</th>
          <th>Date</th>
          <th>Description</th>
        </tr>
    </thead>
  <tbody>
 
    <!-- Function to read the newsletters from database -->
    <% @programme.each do |programme| %>
        <tr>
          <td><%= programme.title %></td>
          <td><%= programme.date %></td>
          <td><%= programme.description %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/croquet/WhatYouNeed.html.erb
<br> </br>

<h1>What You Need</h1>
<p>When you join the Club and start to learn how to play the game you do not need to be involved in any expense as far as equipment is concerned.

Initially you can borrow a club mallet and use it until you are sure that you like the game and until you know what sort of mallet you want to buy for your personal use. The only requirement to start with is that you should wear flat-soled shoes on the lawn to avoid damage.

When you start playing in matches it is suggested that you get "whites" to play in as this is the accepted norm for matches and tournament play.</p>

<p>Get more information via the <a href="http://maria-52696.euw1.actionbox.io/"><b>Home</b></a> page . </p>

app/views/layouts/_footer.html.erb
<footer>
  <p id="footer">  &copy;s <%= Time.now.year %> CHEAM CROQUET & BOWLS CLUB</p>
</footer>

app/views/layouts/_header.html.erb
<header>
   <link rel="stylesheet" type="text/css" href="header.css">
  <p><%=image_tag"logo.png", :size => "150x150"%></p>
  
  <h1>CHEAM CROQUET & BOWLS CLUB</h1>
</header>

app/views/layouts/_navigation.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="navigation.css">
</head>

<div id='cssmenu'>
<nav>
  <ul>
    <li class='active'><%=link_to "Home", root_path %></li>
    <li><%=link_to "About The Club", aboutTheClub_path %></li>
    <li><%=link_to "How To Join", howToJoin_path %></li>
    <li><%=link_to "What You Need", whatYouNeed_path %></li>
    <li><%=link_to "Programme", programme_path %></li>
    <li><%=link_to "News Letters" , newsLetters_path %></li>
    <li><%=link_to "Club Matters" , clubMatters_path %></li>
    <li><%=link_to "How To Get There", howToGetThere_path %></li>
    <% if user_signed_in? %>
    <li><%=link_to "Book A Lawn", bookings_path %></li>
    <% end %>
    <li><%=link_to "Links To Croquet Sites" , links_path %></li>
    <li><%=link_to "Admin Login" , admin_path %></li> 
    <li><%=link_to "Sign Up" , new_user_registration_path %></li> 
    <% if user_signed_in? %>
    <li class='last'><%=link_to "Sign Out" , destroy_user_session_path, :method => :delete %></li> 
    <br> </br>
    <p> </p>
    Signed in as <%= current_user.email %>
    <% else %>
    <li class='last'><%=link_to "Sign In" , new_user_session_path %></li>
    <% end %>    
  </ul>
</nav>
</div>
 

  
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/header' %>
  <p class = 'notice'><%= notice %></p>
  <p class = 'alert'><%= alert %></p>
<%= render 'layouts/navigation' %>
  
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>